language: java
install: true

os: linux
dist: trusty

# - Install SDKMAN
# - Install msttcorefonts, so we have the Verdana font available for diagram generation
# - Install graphviz, so we have the dot binary available for diagram generation
# - Install JDK 13 and GraalVM 20.1 (JDK 11)
before_install:
  - |-
    curl -sL https://get.sdkman.io | bash
    echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
    echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
    source $HOME/.sdkman/bin/sdkman-init.sh
    sudo apt-get update
    echo msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    sudo apt-get install ttf-mscorefonts-installer
    sudo apt-get install -y graphviz
    sdk install java 13.0.2-open || true
    sdk install java 20.1.0.r11-grl || true
    sdk use java 20.1.0.r11-grl
    gu install native-image
    unset _JAVA_OPTIONS
    java -version

before_cache:
  - |-
    rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - |-
      $HOME/.gradle/caches/
      $HOME/.gradle/wrapper/

jobs:
  include:
    # -------------------------------------------
    - stage: build+deploy-release
      name: "Build and deploy Release"
      if:
        tag IS present AND tag =~ /^v.*/
      script: ./gradlew clean test check jacocoRootReport antora
      after_success: bash <(curl -s https://codecov.io/bash)
      deploy:
        - provider: releases
          api_key: "$GITHUB_API_KEY"
          file_glob: true
          file: cli/build/libs/owl-cli-*.jar
          on:
            repo: atextor/owl-cli
          skip_cleanup: true
          draft: false
          tag_name: $TRAVIS_TAG
          target_commitish: $TRAVIS_COMMIT
    # -------------------------------------------
    - stage: build+deploy-snapshot
      name: "Build and deploy Snapshot"
      if:
        tag IS NOT present
      script: ./gradlew clean test check jacocoRootReport nativeImage
      after_success:
        - |-
          bash <(curl -s https://codecov.io/bash)
          git config --local user.name "Travis"
          git config --local user.email "Travis"
          export TRAVIS_TAG=snapshot
          git push -q --delete https://atextor:$GITHUB_API_KEY@github.com/atextor/owl-cli.git $TRAVIS_TAG >/dev/null 2>&1 || true
          git tag $TRAVIS_TAG
      deploy:
        - provider: releases
          api_key: "$GITHUB_API_KEY"
          file:
            - cli/build/libs/owl-cli-snapshot.jar
            - cli/build/bin/owl
          on:
            repo: atextor/owl-cli
            branch: master
          skip_cleanup: true
          overwrite: true
          draft: false
          tag_name: $TRAVIS_TAG
          target_commitish: $TRAVIS_COMMIT
    #     - provider: pages
    #       github_token: "$GITHUB_API_KEY"
    #       keep_history: false
    #       local_dir: build/site
    #       skip_cleanup: true
    #       on:
    #         repo: atextor/owl-cli
    #         branch: master
    # # -------------------------------------------

