language: java
install: true

os: linux
dist: trusty
jdk: openjdk13

before_install:
  - sudo apt-get update
  - sudo apt-get install -y graphviz

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check
  - ./gradlew clean test jacocoRootReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
