site:
  title: owl-cli Documentation
  url: https://atextor.de/owl-cli/
  start_page: main::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
    - url: https://github.com/atextor/owl-cli.git
      tags: [v.*]
      branches: ~
      start_path: docs
ui:
  bundle:
    # UI bundle is built from here: https://github.com/atextor/docs-antora-ui
    url: ./docs/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
    stem: 'asciimath'
  extensions:
    - "@djencks/asciidoctor-mathjax"
