site:
  title: owl-cli Documentation
  url: https://github.com/atextor/owl-cli
  start_page: main::index.adoc
content:
  sources:
    - url: .
      branches: master
      start_path: docs
ui:
  bundle:
    # UI bundle is built from here: https://github.com/atextor/docs-antora-ui
    url: ./docs/ui-bundle.zip
    snapshot: true
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
