// -*- fill-column: 100; -*-
= owl-cli

(Version *{page-component-version}*)

*owl-cli* is a command line tool for ontology engineering. It targets the
https://en.wikipedia.org/wiki/Web_Ontology_Language[Web Ontology Language] (OWL 2) and
https://en.wikipedia.org/wiki/Resource_Description_Framework[RDF]. The current main feature is the
generation of automatically layed out diagrams for an OWL ontology.

You can find the source code on https://github.com/atextor/owl-cli[Github].

image::splash.svg[width=75%]

== Installation

=== Requirements

Things you will need to have installed to run *owl-cli*:

* https://www.graphviz.org/[Graphviz] for the generation of diagrams.
** Install in Windows (using https://chocolatey.org/[Chocolatey]): `choco install graphviz`
** Install in MacOs (using https://brew.sh/[Brew]): `brew install graphviz`
** Install in Ubuntu/Debian Linux: `apt install graphviz`

* If using the executable .jar file: Java (OpenJDK) *11* or newer

=== Download and Install `owl-cli`

Download the pre-built binary for your platform:

* Windows (x86_64): https://github.com/atextor/owl-cli/releases/download/{release-version}/owl-x86_64-windows-{release-version}.exe[owl-x86_64-windows-{release-version}.exe]
* MacOs (x86_64): https://github.com/atextor/owl-cli/releases/download/{release-version}/owl-x86_64-apple-darwin-{release-version}[owl-x86_64-apple-darwin-{release-version}]
* Linux (x86_64): https://github.com/atextor/owl-cli/releases/download/{release-version}/owl-x86_64-linux-{release-version}[owl-x86_64-linux-{release-version}]
* Other platforms or architectures: Please use the executable .jar file: https://github.com/atextor/owl-cli/releases/download/{release-version}/owl-cli-{release-version}.jar[owl-cli-{release-version}.jar]

Rename the binary to `owl.exe` (Windows) or `owl` (MacOs/Linux), put it in your favorite directory
and add this directory to the PATH environment variable:

* Windows: `setx /M path "%path%;C:\your\path\here\"`
* MacOs/Linux: `echo 'export PATH=/your/path/here:$PATH' >> ~/.bashrc; source ~/.bashrc`

[NOTE]
====
If using the executable .jar file, the following commands will make the jar available as `owl`
command as well. This works in MacOs and Linux.

[source,shell]
----
curl -L -o ~/.local/share/owl-cli/owl-cli.jar --create-dirs https://github.com/atextor/owl-cli/releases/download/snapshot/owl-cli.jar
echo 'function owl() { java -jar ~/.local/share/owl-cli/owl-cli.jar $*; }' >> ~/.bashrc
source ~/.bashrc
----
====

After installation, you can use the `owl` command: See xref:usage.adoc[] for more information.

== Building from Source

[[building-executable-jar]]
=== Building the executable JAR from source

*owl-cli* uses Java 15 source features, but the build generates a Java 11-compatible JAR file. This
 means, for building the executable JAR file, you need Java *15*. The `gradle` build forks jobs
 where it expects Java 15 to be installed in a certain place (see <<building-native-image>> for an
 explanation). We rely on the locations as used by https://sdkman.io/[SDKMAN!].

Run the following commands:

[source,shell]
----
# The following commands install SDKMAN!. If you have it installed already, you can skip it.
curl -sL https://get.sdkman.io | bash
echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
source $HOME/.sdkman/bin/sdkman-init.sh

# Use SDKMAN! to install JDK
sdk install java 15.0.2-open
sdk use java 15.0.2-open

# Build the project
git clone https://github.com/atextor/owl-cli.git
cd owl-cli
./gradlew
----

This will build `cli/build/libs/owl-cli-snapshot.jar`, which you then can install locally:

[source,shell]
----
mkdir -p ~/.local/share/owl-cli
cp cli/build/libs/owl-cli-snapshot.jar !$/owl-cli.jar
echo 'function owl() { java -jar ~/.local/share/owl-cli/owl-cli.jar $*; }' >> ~/.bashrc
source ~/.bashrc
----

After that, you can use the `owl` command: See xref:usage.adoc[] for more information.

[[building-native-image]]
=== Building the native image (executable binary) from source

NOTE: The following steps have only been tested on Linux, as of now

*owl-cli* uses Java 15 source features, but the build generates a Java 11-compatible JAR file, which
 is required for the generation of the native image using https://www.graalvm.org/[GraalVM], as
 GraalVM currently does not support Java 15 class files. This means, for building the native image,
 you need both Java *11* (i.e. GraalVM JDK) *and* Java *15*. In particular, the `gradle` build must
 be executed using Java 11, while Java 15 is installed in a certain place where the build can
 find it. We rely on the locations as used by https://sdkman.io/[SDKMAN!].

Run the following commands:

[source,shell]
----
# The following commands install SDKMAN!. If you have it installed already, you can skip it.
curl -sL https://get.sdkman.io | bash
echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
source $HOME/.sdkman/bin/sdkman-init.sh

# Use SDKMAN! to install JDKs
sdk install java 15.0.2-open
sdk install java 21.0.0.2.r11-grl
sdk use java 21.0.0.2.r11-grl

# Build the project
git clone https://github.com/atextor/owl-cli.git
cd owl-cli
./gradlew nativeImagePass2
----

This will build `cli/build/bin/owl`, which you can put anywhere on your `PATH`.

