// -*- fill-column: 100; -*-
= Usage

NOTE: Although the package is called *owl-cli*, the command you invoke is called `owl`.

You can call the built-in overview of commands and arguments via `--help`:

[source,shell]
----
Usage:

Usage: owl [-v] [--help] [--version] [COMMAND]

Description:

Command line tool for ontology engineering

Options:
      --help      Show short help
  -v, --verbose   Specify multiple -v options to increase verbosity,
                  e.g. use `-v`, `-vv` or `-vvv` for more details
      --version   Show current version
Commands:
  ...
----

Other than the general help, you give one argument, the _command_, which will
take its own arguments, for example:

[source,shell]
----
owl diagram --format png
----

Commands that take ontology files as an input support all formats that are
supported by https://github.com/owlcs/owlapi[OWL API], notably
https://www.w3.org/TR/turtle/[RDF/Turtle],
https://www.w3.org/TR/rdf-syntax-grammar/[RDF/XML],
https://www.w3.org/TR/owl-xml-serialization/[OWL/XML] and
https://www.w3.org/TR/owl2-syntax/[OWL Functional Syntax].


[#diagram-command]
== `diagram` Command

The `diagram` command takes an OWL ontology as input and generates an
automatically layouted diagram for it in the SVG or PNG format. This is
implemented by mapping the ontology's axioms into a graph description in the
https://www.graphviz.org/[Graphviz] language, which is passed to its `dot`
layouting engine. Attributes such as fonts can be customized using arguments.

NOTE: As no standardized graphical notation for OWL exists, the diagram notation
used here is described in detail on a separate page:
xref:diagram-notation.adoc[Diagram Notation].

[#diagram-usage]
=== General Usage

General usage: `owl diagram [options] input [output]`, where `input` can be
either an ontology file or `-` (which means: read from standard in) and `output`
can be either an ontology file or `-` (which means: write to standard out). If
`output` is not given, the output filename is the input filename with its file
extension changed, e.g. myontology.ttl -> myontology.svg. If `input` is `-` and
`output` is not given, the output is set to standard out.

[#diagram-options]
=== Options

.diagram Command Options
[cols="<,<,<,<", options="header"]
|===
|Option|Description|Default|Notes

|`--direction`
|Diagram layout direction
|left_to_right
|Possible values: [top_to_bottom, left_to_right]

|`--dotbinary`
|Path to `dot` binary
|dot
|By default, `dot` is searched for in your `$PATH`

|`--fontname`
|Default font
|Verdana
|

|`--fontsize`
|Default font size
|12
|

|`--format`
|Output file format
|svg
|Possible values: [png, svg]

|`--nodefontname`
|Font for nodes
|Verdana
|

|`--nodefontsize`
|Font size for nodes
|Verdana
|

|`--nodemargin`
|The margin to render inside of nodes
|0.05,0.0
|See the https://www.graphviz.org/docs/attrs/margin/[Graphviz
 documentation] for more information

|`--nodeshape`
|Node shape
|box
|See the https://www.graphviz.org/doc/info/shapes.html[Graphviz documentation]
 for more information

|`--nodestyle`
|Node style
|rounded
|See the https://www.graphviz.org/docs/attrs/style/[Graphviz documentation] for more information

|`--fgcolor`
|Color for boxes, fonts and edges
|white
|See the https://www.graphviz.org/docs/attrs/bgcolor/[Graphviz documentation] for more information

|`--bgcolor`
|Background color for the generated diagram
|white
|See the https://www.graphviz.org/docs/attrs/bgcolor/[Graphviz documentation] for more information

|===

[#diagram-example-usage]
=== Example Usage

Simple invocation with default arguments:

[source,shell]
----
# Will create myontology.svg
owl diagram myontology.ttl
----

Invocation where the output is specified as standard out and piped to
https://imagemagick.org/script/convert.php[convert] to create a different format:

[source,shell]
----
owl diagram myontology.ttl - | convert - myontology.jpg
----

Invocation where an ontology is downloaded, some terms are filtered and then
piped to owl diagram:
[source,shell]
----
curl http://www.ontologydesignpatterns.org/cp/owl/partof.owl | \
grep -v 'comment|cpannotation|versionInfo' | owl diagram - partof.svg
----

[#write-command]
== `write` Command


[#write-usage]
=== General Usage

The `write` command takes any RDF file in
https://www.w3.org/TR/turtle/[RDF/Turtle],
https://www.w3.org/TR/rdf-syntax-grammar/[RDF/XML],
https://www.w3.org/TR/n-triples/[RDF N-Triples] or
https://www.w3.org/TeamSubmission/n3/[N3] format as input and writes it out in any of those formats.
When writing RDF/Turtle, the formatting of the resulting output can be configured extensively, as
this makes use of the https://github.com/atextor/turtle-formatter[turtle-formatter library].

General usage: `owl write [options] input [output]`, where `input` can be either an RDF file, a URL
(starting with `http` or `https`) or `-` (which means: read from standard in) and `output` can be
either an RDF file or `-` (which means: write to standard out). If
`output` is not given, the output filename is the input filename with its file
extension changed, e.g. myontology.nt -> myontology.ttl. If `input` is `-` or a URL and
`output` is not given, the output is set to standard out.

[#write-options]
=== Options

.write Command Options
[cols="<,<,<,<", options="header"]
|===
|Option|Description|Default|Notes

|`-o`, `--output`
|Output file format
|turtle
|Possible values: [turtle, rdfxml, ntriple, n3]

|`-i`, `--input`
|Input file format
|turtle
|Possible values: [turtle, rdfxml, ntriple, n3]

|`-p`, `--prefix`
|Known prefix with corresponding URI to add as `@prefix` when serializing Turtle.
|[rdf, rdfs, xsd, owl, dcterms]
|This can be given multiple times, for multiple prefixes. You can specify a well-known prefix
 (currently: rdf, rdfs, xsd, owl, dcterms), e.g. `-prdf` or `--prefix=rdf` or any other prefix with its url:
 `-pfoo=http://example.com/` or `--prefix=foo=http://example.com/`. To set the empty prefix, use
 `-p==http://example.com/` or `--prefix==http://example.com`.

|`--prefixAlign`
|Alignment of `@prefix` statements
|off
|Possible values: [left, off, right]

|`--encoding`
|Output encoding
|utf_8
|Possible values: [latin1, utf_16_be, utf_16_le, utf_8, utf_8_bom]

|`--doubleFormat`
|Defines how double numbers are formatted
|`0.\####E0`
| See
  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/DecimalFormat.html[here]
  for more information on the format

|`--endOfLine`
|End of line style
|lf
|Possible values: [cr, crlf, lf]

|`--indent`
|Indent style
|space
|Possible values: [tab, space]. Note that when choosing `tab`, `alignPredicates` and `alignObjects`
 are automatically treated as `false`.

|`--firstPredicateInNewLine`
|Write first predicate in new line of block
|
|Switched off by default

|`--writeRdfType`
|Write `rdf:type` instead of `a`
|
|Switched off by default

|`--useCommaByDefault`
|Use commas for multiple objects
|
|Switched off by default

|`--noCommaForPredicate`
|Use no commas for multiple objects for this predicate
|
|This can be given multiple times.

|`--useLongLiterals`
|Use long form for literals, e.g. `"5"^^xsd:integer` instead of `5`
|
|Switched off by default

|`--alignObjects`
|Align objects for same predicates
|
|Switched off by default

|`--alignPredicates`
|Align predicates for same subjects
|
|Switched off by default

|`--continuationIndentSize`
|Indentation size after forced line wraps
|4
|

|`--doNotInsertFinalNewline`
|Do not insert newline at end of file
|
|Switched off by default

|`--indentSize`
|Indentation size in spaces
|2
|

|`--keepUnusedPrefixes`
|Keeps prefixes that are not part of any statement
|
|Switched off by default

|`--prefixOrder`
|Sort order for prefixes (if they appear in a model)
|[rdf, rdfs, xsd, owl]
|Add this switch multiple times, once for each prefix, in the desired order

|`--subjectOrder`
|Sort order for subjects by type (if they appear in a model)
|[`rdfs:Class`, `owl:Ontology`, `owl:Class`, `rdf:Property`, `owl:ObjectProperty`, `owl:DatatypeProperty`, `owl:AnnotationProperty`, `owl:NamedIndividual`, `owl:AllDifferent`, `owl:Axiom`]
|Add this switch multiple times, once for each subject type, in the desired order

|`--predicateOrder`
|Sort order for predicates (if they appear on a subject)
|[`rdf:type`, `rdfs:label`, `rdfs:comment`, `dcterms:description`]
|Add this switch multiple times, once for each predicate, in the desired order

|`--objectOrder`
|Sort order for objects
| [`owl:NamedIndividual`, `owl:ObjectProperty`, `owl:DatatypeProperty`, `owl:AnnotationProperty`,
  `owl:FunctionalProperty`, `owl:InverseFunctionalProperty`, `owl:TransitiveProperty`,
  `owl:SymmetricProperty`, `owl:AsymmetricProperty`, `owl:ReflexiveProperty`, `owl:IrreflexiveProperty`]
|Add this switch multiple times, once for each object type, in the desired order

|`--anonymousNodeIdPattern`
|Name pattern for blank node IDs
|`_:gen0`
|A `0` inside the pattern will be replace with the index of the respective blank node

|===


[#write-example-usage]
=== Example Usage

Simple invocation with default arguments:

[source,shell]
----
# Read myontology.ttl and print it in formatted Turtle format
owl write myontology.ttl

# Read myontology.owl in RDF/XML format and print it in formatted Turtle format, writing output.ttl
owl write -i rdfxml myontology.owl output.ttl

# Read myontology.n3 in N3 format and print it in formatted Turtle format to stdout
owl write -i n3 myontology.n3

# Read myontology.nt in N-Triples format and print it in RDF/XML format to stdout
owl write -i ntriple -o rdfxml myontology.nt
----

Read an N-Triples file and write formatted Turtle, while also configuring which prefixes should be used:

[source,shell]
----
owl write -prdf -powl -pxsd -p'ex=http://example.com#' -i ntriple myontology.nt
----

Read a Turtle file and print it out, while configuring the output's formatting and prefix order:

[source,shell]
----
owl write --indentSize 4 --writeRdfType --prefixOrder owl --prefixOrder rdf myontology.turtle
----

Read a remote ontology in RDF/XML format and print it in formatted Turtle format:
[source,shell]
----
owl write -i rdfxml 'http://www.ontologydesignpatterns.org/cp/owl/partof.owl'
----
