name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number'
        required: true
jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest, ubuntu-20.04, macos-latest ]
        include:
          - os: windows-latest
            binary-file-extension: .exe
          - os: ubuntu-20.04
            binary-file-extension: ''
          - os: macos-latest
            binary-file-extension: ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        # - Install msttcorefonts, so we have the Verdana font available for diagram generation
        # - Install graphviz, so we have the dot binary available for diagram generation
        run: |-
          find /etc/apt -type f -name '*.list' -exec sed -i -e '/dl.bintray.com\/sbt/d' "{}" \;
          sudo apt-get update
          echo msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo apt-get install -y graphviz
          sudo apt-get install -y build-essential libz-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        # - Install graphviz, so we have the dot binary available for diagram generation
        run: |-
          choco install zip --execution-timeout=600
          choco install unzip --execution-timeout=600
          choco install graphviz --execution-timeout=600
        shell: bash

      - name: Install dependencies (MacOs)
        if: runner.os == 'macOS'
        # - Install graphviz, so we have the dot binary available for diagram generation
        run: |-
          brew install graphviz

      - name: Setup JDK
        uses: graalvm/setup-graalvm@b8dc5fccfbc65b21dd26e8341e7b21c86547f61b # v1
        with:
          java-version: '17.0.10'
          distribution: 'graalvm'
          components: 'native-image,js'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Pagefile (Windows)
        if: runner.os == 'Windows'
        # Fix for "LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)":
        # This seems to be caused by running out of memory; increasing page file
        # size suggested here:
        # https://github.com/actions/virtual-environments/issues/3420#issuecomment-861342418
        uses: al-cheb/configure-pagefile-action@86589fd789a4de3e62ba628dda2cb10027b66d67 # v1.3
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"

      - name: Set Swap Space (Linux)
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c # master
        with:
          swap-size-gb: 12

      - name: Build and run tests
        run: |
          # Required for reactor dependencies
          mvn -B clean install -DskipTests
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.release_version }}
          mvn -B versions:commit

          # Actual build
          mvn -B clean install
          mvn -B clean verify -pl cool-rdf-cli -Pnative
          mv target/cool${{ matrix.binary-file-extension }} target/cool-${{ runner.os }}-${{ runner.arch }}${{ matrix.binary-file-extension }}
        shell: bash

      - name: Switch to Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Test executable jar on Temurin
        run: |
          mvn -B -Dskip.maven.surefire -pl cool-rdf-cli failsafe:integration-test@default

      - name: Compress native executable
        # UPX doesn't work on mac
        if: runner.os != 'macOS'
        uses: crazy-max/ghaction-upx@0fc45e912669ba9e8fa2b430e97c8da2a632e29b # v3.0.0
        with:
          version: latest
          files: cool-rdf-cli/target/cool-${{ runner.os }}-${{ runner.arch }}${{ matrix.binary-file-extension }}
          args: -9

      - name: Upload workspace
        # We need to upload the generated jars for every submodule,
        # so that we have it available for release. Also includes the Linux executable.
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

      - name: Upload executable
        if: ${{ runner.os == 'Windows' || runner.os == 'macOS' }}
        uses: actions/upload-artifact@v4
        with:
          name: cool-rdf-cli-${{ runner.os }}
          # .dlls only exist on Windows of course
          path: |
            cool-rdf-cli/target/cool-${{ runner.os }}-${{ runner.arch }}${{ matrix.binary-file-extension }}
            cool-rdf-cli/target/*.dll

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.PGP_KEY }}
          gpg-passphrase: PGP_KEY_PASSWORD
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          overwrite-settings: false

      - name: Fetch source tree
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Release to Maven Central
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mvn -B -DreleaseVersion=${{ github.event.inputs.release_version }} \
            -DskipTests -Darguments="-DskipTests" release:prepare release:release
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}

      - name: Fetch Windows executable
        uses: actions/download-artifact@v4
        with:
          name: cool-rdf-cli-Windows

      - name: Fetch macOS executable
        uses: actions/download-artifact@v4
        with:
          name: cool-rdf-cli-macOS

      - name: Create Windows zip
        run: |
          cd target
          zip -9 -r cool-rdf-cli-Windows-X64.zip cool*.exe *.dll

      - name: Create GitHub release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844v1 # v0.1.15
        with:
          body: "Release version ${{ github.event.inputs.release_version }}"
          tag_name: v${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
          files: |
            target/cool-rdf-cli-${{ github.event.inputs.release_version }}.jar
            target/cool-rdf-cli-Linux-X64
            target/cool-rdf-cli-Windows-X64.zip
            target/cool-rdf-cli-macOS-X64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e # 4.5.0
        with:
          branch: gh-pages
          folder: docs/target/docs
